# Permalinks
permalink:           pretty

# Setup
title:               Jeremy Chow:
tagline:             Learning Data Science
url:                 http://jeremyrchow.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jeremy Chow
  url:               N/A
  email:             jeremyrchow@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jeremyrchow/jeremyrchow.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
